# Generated by Django 4.0.2 on 2022-03-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='TiposVehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.estados')),
            ],
            options={
                'db_table': 'tiposvehiculos',
            },
        ),
        migrations.CreateModel(
            name='TiposDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.estados')),
            ],
            options={
                'db_table': 'tiposdocumento',
            },
        ),
        migrations.CreateModel(
            name='Referidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('nombreReferido', models.CharField(max_length=200)),
                ('apellidoReferido', models.CharField(max_length=200)),
                ('documentoReferido', models.CharField(max_length=100)),
                ('telefonoReferido', models.CharField(max_length=100, null=True)),
                ('urlFoto1', models.CharField(max_length=200)),
                ('urlFoto2', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=500)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField()),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.estados')),
                ('tipoDocumento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tiposdocumento')),
            ],
            options={
                'db_table': 'referidos',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.estados')),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Conveniocda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('placa', models.CharField(max_length=100)),
                ('chasis', models.CharField(max_length=200, null=True)),
                ('valor', models.CharField(default='$', max_length=200)),
                ('observaciones', models.CharField(max_length=500)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField()),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.empresas')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.estados')),
                ('tipodocumento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tiposdocumento')),
                ('tipovehiculo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tiposvehiculo')),
            ],
            options={
                'db_table': 'conveniocda',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100, null=True)),
                ('ubicacion1', models.CharField(max_length=200, null=True)),
                ('ubicacion2', models.CharField(max_length=200, null=True)),
                ('correo', models.CharField(default='', max_length=100, null=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaModificacion', models.DateTimeField()),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.estados')),
                ('tipoDocumento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.tiposdocumento')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
