# Generated by Django 4.0.2 on 2022-03-03 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_conveniocda_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historialconvenios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.CharField(max_length=500)),
                ('fecha', models.DateTimeField()),
                ('convenio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.conveniocda')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.estados')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historialconvenios',
            },
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.empresas')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empresausuario',
            },
        ),
    ]
