# Generated by Django 4.0.2 on 2022-03-05 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_historialconvenios_empresausuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conveniocda',
            options={'permissions': (('CDA', 'Permisos CDA'), ('GANE', 'Permisos GANE'), ('SUPERGIROS', 'Permisos SuperGiros'))},
        ),
    ]
