# Generated by Django 3.0 on 2022-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_conveniocda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechasrevision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'fechasrevision',
            },
        ),
        migrations.AlterField(
            model_name='conveniocda',
            name='valor',
            field=models.CharField(default='$ ', max_length=200),
        ),
    ]
