# Generated by Django 3.0 on 2022-03-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_conveniocda_revision'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conveniocda',
            unique_together={('placa', 'revision')},
        ),
    ]
